### ISSUE TITLE
Wont connect look like a geth have some problems.

### ISSUE THREAD

**Issue by StianNOR** [rhmaxdotorg/pulsechain-validator#13]
![image](https://user-images.githubusercontent.com/82333847/236803069-83fb5f18-6449-4139-9051-f07333fcd6e6.png)

**Comment by StianNOR** [comment]
maybe main issue is this. I getting disconnected from server on lighthouse build:

![image](https://user-images.githubusercontent.com/82333847/236818345-452267f5-d83f-4fcd-93ef-a83bda025cd5.png)

**Comment by rhmaxdotorg** [comment]
It looks like you're getting disconnected from the server due to a network timeout before the setup can complete (999/1000 can take longer than the rest of the process).

Its not a script problem, but more of a network connection stability issue (usually). You can run the script in a tmux terminal to help.

Learn how to use tmux here: https://www.howtogeek.com/671422/how-to-use-tmux-on-linux-and-why-its-better-than-screen/

So if you get disconnected, your session keeps going and you can resume using the tmux attach commands.
