### ISSUE TITLE
Recovery after power outage

### ISSUE THREAD

**Issue by dkim777** [rhmaxdotorg/pulsechain-validator#28]
I lost power for about 12hours and restarted the Validator PC.
It's been over 24hours but nothing is being added to my account.
all other method of checking documented in this repo shows everything is syned and working ok.
any idea how long it will take to recover or do I need to do something else?
Thanks.

**Comment by dkim777** [comment]
It recovered after about two days...

**Comment by rhmaxdotorg** [comment]
hey @dkim777 ! 

Just saw this as I was traveling for a couple days. Glad it all worked out, however 2 days to start earning again sounds like a long time... hm.

Wondering if the clients needed to rebuild the db or something and it took a while to do so. I'm testing migration to another server right now which is taking some time (probably just sync time), so that will be interesting to see how long it takes as well.
